# Generated by Django 4.1.2 on 2022-11-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_x', models.CharField(max_length=50)),
                ('data_y', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticData_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_x', models.CharField(max_length=50)),
                ('data_y', models.CharField(max_length=50)),
            ],
        ),
    ]
