# Generated by Django 4.1.2 on 2022-11-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboarddata_statisticdata_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatisticData_2',
        ),
    ]
